### ISSUE TITLE
Configuring nb_black as a pre-commit hook

### ISSUE THREAD

**Issue by mbaudin47** [dnanhkhoa/nb_black#21]
I commonly use black as a pre-commit git hook. To do this, I create the file .pre-commit-config.yaml with the following content:
```
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
```

It would be extremely convenient to have the same feature with nb_black.
